language: R
sudo: false
cache:
  - packages
  - pip

addons:
  apt:
    packages:
      - python3-pip

before_install:
  - pip3 install --user boto3

before_deploy: Rscript -e 'install.packages("pkgdown")'
after_success:
  - Rscript -e 'covr::codecov()'
