language: R
sudo: false
cache:
  - packages
  - pip

before_install:
  - sudo pip install --upgrade pip
  - python3-pip
  - pip3 install --user boto3

before_deploy: Rscript -e 'install.packages("pkgdown")'
after_success:
  - Rscript -e 'covr::codecov()'
