language: R
sudo: false
cache:
  - packages
  - pip

before_install:
  - pip install boto3

before_deploy: Rscript -e 'install.packages("pkgdown")'
after_success:
  - Rscript -e 'covr::codecov()'

deploy:
  script: Rscript -e 'pkgdown::deploy_site_github()'